/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_mavka_angle_NativeCallsClass */

#ifndef _Included_com_example_mavka_angle_NativeCallsClass
#define _Included_com_example_mavka_angle_NativeCallsClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_mavka_angle_NativeCallsClass
 * Method:    getA
 * Signature: (DDDDDI)D
 */
JNIEXPORT jdouble JNICALL Java_com_example_mavka_angle_NativeCallsClass_getA
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble, jdouble, jint);

#ifdef __cplusplus
}
#endif
#endif
